ALTER SYSTEM SET OPEN_CURSORS=5000 SID='*' SCOPE=BOTH;

ALTER SESSION SET CONTAINER = freepdb1;

CREATE USER "MUD" IDENTIFIED BY letmein;

GRANT ALL PRIVILEGES TO MUD;
GRANT UNLIMITED TABLESPACE TO MUD;

CREATE ROLE MUD_INSERT;
CREATE ROLE MUD_DELETE;
CREATE ROLE MUD_UPDATE;
CREATE ROLE MUD_SELECT;